"""empty message

Revision ID: 253cc43b42d1
Revises: 6694876faed9
Create Date: 2024-02-09 21:49:33.688000

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '253cc43b42d1'
down_revision: str | None = '6694876faed9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('discount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dishes', 'discount')
    # ### end Alembic commands ###
