"""empty message

Revision ID: 6694876faed9
Revises:
Create Date: 2024-01-20 01:27:18.630543

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6694876faed9'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menus',
                    sa.Column('title', sa.String(length=64), nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('description', sa.String(length=512), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('title')
                    )
    op.create_table('submenus',
                    sa.Column('menu_id', sa.UUID(), nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('title', sa.String(length=64), nullable=False),
                    sa.Column('description', sa.String(length=512), nullable=True),
                    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('menu_id', 'title')
                    )
    op.create_table('dishes',
                    sa.Column('price', sa.DECIMAL(scale=2), nullable=False),
                    sa.Column('submenu_id', sa.UUID(), nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('title', sa.String(length=64), nullable=False),
                    sa.Column('description', sa.String(length=512), nullable=True),
                    sa.ForeignKeyConstraint(['submenu_id'], ['submenus.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('submenu_id', 'title')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dishes')
    op.drop_table('submenus')
    op.drop_table('menus')
    # ### end Alembic commands ###
