"""empty message

Revision ID: 6dbba60e03ca
Revises: 9b6a0e8f0302
Create Date: 2024-01-19 19:08:22.581774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dbba60e03ca'
down_revision: Union[str, None] = '9b6a0e8f0302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dishes', 'title',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('dishes', 'description',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.drop_constraint('dishes_title_key', 'dishes', type_='unique')
    op.create_unique_constraint(None, 'dishes', ['submenu_id', 'title'])
    op.alter_column('menus', 'title',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('menus', 'description',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('submenus', 'title',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('submenus', 'description',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.drop_constraint('submenus_title_key', 'submenus', type_='unique')
    op.create_unique_constraint(None, 'submenus', ['menu_id', 'title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submenus', type_='unique')
    op.create_unique_constraint('submenus_title_key', 'submenus', ['title'])
    op.alter_column('submenus', 'description',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
    op.alter_column('submenus', 'title',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('menus', 'description',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
    op.alter_column('menus', 'title',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_constraint(None, 'dishes', type_='unique')
    op.create_unique_constraint('dishes_title_key', 'dishes', ['title'])
    op.alter_column('dishes', 'description',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
    op.alter_column('dishes', 'title',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
