version: "3.8"

services:
  db_test:
    image: postgres:15.1-alpine
    container_name: ylab_db_test
    environment:
      POSTGRES_DB: "ylab_dishes_db_test"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "ylab_dishes_db_test", "-U", "postgres" ]
      interval: 3s
      timeout: 3s
      retries: 12

  redis_test:
    image: redis:7.0-alpine
    container_name: ylab_redis_test
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5

  app_test:
    build:
      context: .
    container_name: ylab_app_test
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      db_test:
        condition: service_healthy
    command: sh -c "pytest -v"
