version: "3.8"

services:
  db:
    image: postgres:15.1
    container_name: ylab_db
    env_file:
      - .env

  app:
    build:
      context: .
    container_name: ylab_app
    env_file:
      - .env
    depends_on:
      - db
    command: ["sh", "/app/docker/app_entrypoint.sh" ]
#    entrypoint: ./app_entrypoint.sh
    ports:
      - 8000:8000
