version: "3.8"

services:
  db:
    image: postgres:15.1-alpine
    container_name: ylab_db
    environment:
      POSTGRES_DB: "ylab_dishes_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "ylab_dishes_db", "-U", "postgres" ]
      interval: 3s
      timeout: 3s
      retries: 12
    ports:
      - "5432:5432"

  redis:
    image: redis:7.0-alpine
    container_name: ylab_redis
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5

  app:
    build:
      context: .
    container_name: ylab_app
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    command: sh -c "alembic upgrade head && uvicorn app.main:app --reload --host 0.0.0.0"
    ports:
      - 8000:8000

  celery:
    build:
      context: .
    container_name: ylab_celery
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    command: sh -c "celery -A app.celery:celery worker --loglevel=INFO -B"
