version: "3.8"

services:
  db:
    image: postgres:15.1-alpine
    container_name: ylab_db_test
    environment:
      POSTGRES_DB: "ylab_dishes_db_test"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    container_name: ylab_app_test
    env_file:
      - .env
    depends_on:
      - db
    command: sh -c "alembic upgrade head && pytest -v"
    ports:
      - 8000:8000
