[tool.ruff]

line-length = 120

exclude = ["migrations"]

[tool.black]

line-length = 120

extend-exclude = "migrations"

[tool.isort]

extend_skip = [".gitignore", ".dockerignore", ".env", ".env.*", "migrations"]